### ISSUE TITLE
Badge for compliant projects?

### ISSUE THREAD

**Issue by MarcoGorelli** [trailofbits/are-we-pep740-yet#6]
Hey, thanks for this, and for the [talk at SOSS Fusion](https://www.youtube.com/watch?v=GxG3ygbAn7E)!

I have a question/suggestion - should there be an official badge, which projects can put on their readme, so signify that their project provides attestations?

I'm interested in this for [Narwhals](https://github.com/narwhals-dev/narwhals) where I think I've done things correctly on the publishing side:
```python
In [7]: packages = [{'name': 'narwhals'}]

In [8]: annotate_wheels(packages)
Getting wheel data...
1 1 narwhals

In [9]: packages
Out[9]:
[{'name': 'narwhals',
  'wheel': True,
  'value': 1,
  'css_class': 'success',
  'icon': '🔏',
  'title': 'This package provides attestations.'}]
```
and wanted to know what the best way (if any) would be to communicate PEP740 compliance on the README

**Comment by woodruffw** [comment]
Thanks for filing an issue @MarcoGorelli!

We don't have any kind of official badge for this, but you could make one for yourself using <https://shields.io>. 

I played around with shields' dynamic XML support, and came up with this:

```
https://img.shields.io/badge/dynamic/xml?url=https%3A%2F%2Fpypi.org%2Fsimple%2Fsampleproject%2F&query=%2F%2Fa%5B%40data-provenance%5D%5Blast()%5D&logo=pypi&label=PEP%20740
```

which renders as:

![Dynamic XML Badge](https://img.shields.io/badge/dynamic/xml?url=https%3A%2F%2Fpypi.org%2Fsimple%2Fsampleproject%2F&query=%2F%2Fa%5B%40data-provenance%5D%5Blast()%5D&logo=pypi&label=PEP%20740)

This isn't quite perfect though, since shields doesn't seem to support XPath functions like booleans, so it returns the mostly recently attested file (or none) instead of a bool.

You can also experiment with it a bit yourself here: <https://shields.io/badges/dynamic-xml-badge>

(You might also be able to use PyPI's JSON API + dynamic JSON in shields for this; I didn't try!)

Edit: the above is also not clickable in a nice way, but that could also be done with their badge builder.

**Comment by MarcoGorelli** [comment]
thanks @woodruffw ! sure, i've done that
